import {__,concat,replace,tap,reduce,map,pipe,includes,all,difference,filter,pluck,unnest,assoc,converge,sortBy,identity} from "ramda"
import {getWhatCategories} from "./getWhatCategories.js"

/**
 * Check if category A (parent) fully includes category B (child)
 * i.e. all elements of B exist in A.
 */
let categoryIncludes = c1 => c2 => 
  c1.category !== c2.category
         && all( includes( __
                         , c1.elements
                         )
               , c2.elements
               )

/*
  c1 => c2 => 
  c1.category !== c2.category
         && all( includes( __
                         , c1.elements
                         )
               , c2.elements
               )
               */

/**
 * Given all categories, add a `children` property to each one
 * listing the names of the categories it includes.
 */
const setChildren =
  cs => cat1 =>
    assoc( 'children'
         , pipe( filter(categoryIncludes(cat1))
               , pluck('category')
               ) (cs)
         , cat1
         )

/**
 * Given all categories, remove from each category any elements
 * that already belong to one of its child categories.
 */
const x = categories => cat1 => pipe
  ( filter(cat2 => includes(cat2.category, cat1.children))
  , pluck('elements')
  , unnest
  ) (categories)

const removeChildElements =
  categories => category =>
    difference( category.elements
              , x(categories)(category)
              )

const scssFileHead =
`/* 
* This file is automatically generated
*/

`
export const generateSCSSVars =
  categories => pipe
    ( converge( map, [setChildren, identity] )
    , tap(console.log)
    , sortBy( x => x.elements.length)
    , categories => map( converge
                 ( assoc('elements')
                 , [removeChildElements(categories), identity]
                 )
               , categories
               )
     , map( c => ({...c,scss: [ ...c.children.map(x=>'$'+x)
                              , ...c.elements
                              ].join(', ')
                  }))
    , reduce( (acc,cur) => `${acc}$${cur.category}: ${cur.scss};`
            , ""
            )
    , replace(/;/g,';\n')
    , concat(scssFileHead)
    )(categories)
