import {__,concat,replace,tap,reduce,map,pipe,includes,all,difference,filter,pluck,unnest,assoc,converge,sortBy,identity} from "ramda"
import {getWhatCategories} from "./getWhatCategories.js"

let categoryIncludes =
  (c1)=>(c2) => c1.category !== c2.category
         && all( includes( __
                         , c1.elements
                         )
               , c2.elements
               )

let removeChildElements =
  cs => cat1 =>
    difference( cat1.elements
                , pipe
                  ( filter(cat2 => includes(cat2.category, cat1.children))
                  , pluck('elements')
                  , unnest
                  )(cs)
                 )
const setChildren =
  cs => cat1 =>
    assoc( 'children'
         , pipe( filter(categoryIncludes(cat1))
               , pluck('category')
               ) (cs)
         , cat1
         )

const scssFileHead =
`/* 
* This file is automatically generated
*/

`
export const generateSCSSVars =
  categories => pipe
    ( converge( map, [setChildren, identity] )
    , sortBy( x => x.elements.length)
    , cs => map( converge
                 ( assoc('elements')
                 , [removeChildElements(cs), identity]
                 )
               , cs
               )
     , map( c => ({...c,scss: [ ...c.children.map(x=>'$'+x)
                              , ...c.elements
                              ].join(', ')
                  }))
  
    , reduce( (acc,cur) => `${acc}$${cur.category}: ${cur.scss};`
            , ""
            )
    , replace(/;/g,';\n')
    , concat(scssFileHead)
    )(categories)
